# Generated by Django 5.0.1 on 2024-01-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('passing_out_date', models.DateField()),
                ('student_image', models.ImageField(blank=True, null=True, upload_to='student_images/')),
            ],
        ),
    ]
